Arrays
Punicorn/punicorn.github.io pull request #2
Opened 2017-04-01 11:00 UTC by Punicorn

Interesting. "unique" doesn`t exactly works with forEach method.
P.S. Sorry for delay. I was sick about a week.

2017-04-04 19:21 UTC, NikitaSedyx requested changes

2017-04-04 19:21 UTC, NikitaSedyx commented on 2.Arrays/arrays.js
> +	return arr instanceof Array;
2 spaces

2017-04-04 19:21 UTC, NikitaSedyx commented on 2.Arrays/arrays.js
> +function isArray2(arr) {
this function doesn't make any sense

2017-04-04 19:21 UTC, NikitaSedyx commented on 2.Arrays/arrays.js
> +function range(from, to, step) {
cases should work:
range(10) [0..9]
range(1, 10) [1..9]
range(1, 10, 3) [1, 4, 7]
range(10, null, 3) [0, 3, 6, 9]
range(10, null) the same with range(10)
range(-2, -5) []
range(-5, -2) [-5, -4, -3]
range(-5, -2, 2) [-5, -3]
range(-5, -2, -2) []
range(-5, null, 2) [] 
range(-5, null, -2) [0, -2, -4]
range(-10, -20, -5) [-10, -15]
range(-20, -10, -5)
currently I have infinity loop for some cases

2017-04-04 19:21 UTC, NikitaSedyx commented on 2.Arrays/arrays.js
> +		(arr[i] == true) && (newArr.push(arr[i]));
1. brackets are not required here
2.  `arr[i] && newArr.push(arr[i])` should work

2017-04-04 19:21 UTC, NikitaSedyx commented on 2.Arrays/arrays.js
> +		return x == true;
`return x`?

2017-04-04 19:21 UTC, NikitaSedyx commented on 2.Arrays/arrays.js
> +	(n === undefined)  && (n = 1);
you have 2 spaces after the 1 condition

2017-04-04 19:21 UTC, NikitaSedyx commented on 2.Arrays/arrays.js
> +	return arr.slice(0, -n);
when n is negative value like -5 you will have arr + [undef, undef, undef, undef, undef]

2017-04-04 19:21 UTC, NikitaSedyx commented on 2.Arrays/index.html
> +  	<header>
2 spaces for html too

2017-04-04 19:21 UTC, NikitaSedyx commented on 2.Arrays/index.html
> +  	<article>
docs suggests to use headers inside articles and sections

2017-04-04 19:21 UTC, NikitaSedyx commented on 2.Arrays/index.html
> +  	<main>
imo it's a bit strange you have articles outside main content

2017-04-04 19:46 UTC, Punicorn commented on 2.Arrays/arrays.js
> +function isArray2(arr) {
Which of these? I`ve found both in "JavaScript. The Definitive Guide" by David Flanagan, chapter 7.10.

2017-04-05 12:56 UTC, NikitaSedyx commented on 2.Arrays/arrays.js
> +function isArray2(arr) {
you just wrapped standard function, there is no sense in this action

2017-04-06 13:09 UTC, NikitaSedyx requested changes
basically looks good, please several comments

2017-04-06 13:09 UTC, NikitaSedyx commented on 2.Arrays/arrays.js
> +function isArray2(arr) {
don't see it has been changed. please look at previous comment

2017-04-06 13:09 UTC, NikitaSedyx commented on 2.Arrays/arrays.js
> +  return(arr);
`return arr`? it will work without brackets

2017-04-06 13:09 UTC, NikitaSedyx commented on 2.Arrays/arrays.js
> +  if (!to) {
`to` can be 0, !0 is false

2017-04-06 16:42 UTC, NikitaSedyx commented on 2.Arrays/arrays.js
> +  return Array.isArray(arr);
this should be removed. and you should have 2 functions with return instanceof and Object.prototype.toString.call

2017-04-06 16:43 UTC, NikitaSedyx approved these changes

2017-04-06 16:55 UTC, merged