LastFM API
Punicorn/punicorn.github.io pull request #4
Opened 2017-04-19 10:38 UTC by Punicorn

callback url

2017-04-24 06:59 UTC, NikitaSedyx requested changes

2017-04-24 06:59 UTC, NikitaSedyx commented on 4.LastFM/lastfmLoader.js
> +    var URL = this.url + 'api_key=' + this.key + '&' + this.query;
I think it's possible to pass `url` argument without `?` like (null, 'try_me')
in this case URL is `try_meapi_key=`
I suggest to break url and query string

2017-04-24 06:59 UTC, NikitaSedyx commented on 4.LastFM/lastfmLoader.js
> +        if (type.indexOf('application/json') + 1 &&
it should be one `if` with  `request.readyState === 4 && request.status === 200`

2017-04-24 06:59 UTC, NikitaSedyx commented on 4.LastFM/artistInfoLoader.js
> +    var artistQuery = /\w{8}-\w{4}-\w{4}-\w{4}-\w{12}/.test(artist)?
it looks like copy paste with 
```
+  this.isMbid = (function() {
+    if(/\w{8}-\w{4}-\w{4}-\w{4}-\w{12}/.test(artist)) {
```

2017-04-24 06:59 UTC, NikitaSedyx commented on 4.LastFM/usageExample.js
> +var loader2 = new TopArtistsLoader(3, 4);
what I can suggest for you here: what about to pass parameters in load function? in this case you don't need to create objects everytime when you want to send request with another query
`load(params, function(data) {console.log(data})`
where params is `{page: 2, limit: 10}`

2017-05-03 17:34 UTC, Punicorn commented on 4.LastFM/lastfmLoader.js
> +    var URL = this.url + 'api_key=' + this.key + '&' + this.query;
"to break url and query string" - what do you mean by that?

2017-05-03 17:38 UTC, Punicorn commented on 4.LastFM/lastfmLoader.js
> +        if (type.indexOf('application/json') + 1 &&
Single "if" that contains "type.indexOf..."? Or should I cut off the second "if" and left the first as it is?

2017-05-05 10:54 UTC, NikitaSedyx commented on 4.LastFM/lastfmLoader.js
> +    var URL = this.url + 'api_key=' + this.key + '&' + this.query;
I mean url is `http://ws.audioscrobbler.com/2.0/` and query params are `api_key`, `author`, `format` etc

2017-05-05 10:54 UTC, NikitaSedyx commented on 4.LastFM/lastfmLoader.js
> +        if (type.indexOf('application/json') + 1 &&
union them

2017-05-06 05:32 UTC, NikitaSedyx reviewed
it's fine but you didn't use classes

2017-05-07 15:59 UTC, NikitaSedyx requested changes

2017-05-07 15:59 UTC, NikitaSedyx commented on 4.LastFM/js/lastfmLoader.js
> +  this.getQuery = function(){};
it could be prototype method

2017-05-07 15:59 UTC, NikitaSedyx commented on 4.LastFM/js/albumInfoLoader.js
> +    var query = this.isMbid(this.params.mbid)?
it's unreadable, please use if for long lines

2017-05-07 15:59 UTC, NikitaSedyx commented on 4.LastFM/js/lastfmLoader.js
> +  this.getQuery = function(){};
also please read about https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent
it can be here

2017-05-08 14:06 UTC, NikitaSedyx approved these changes
nits

2017-05-08 14:06 UTC, NikitaSedyx commented on 4.LastFM/js/lastfmLoader.js
> +  '&format=' + encodeURIComponent(this.params.format) + '&method=' +
nit: spaces for readability

2017-05-08 14:06 UTC, NikitaSedyx commented on 4.LastFM/js/lastfmLoader.js
> +      callback(JSON.parse(decodeURI(request.responseText)));
I think `JSON.parse` is enough

2017-05-08 14:06 UTC, NikitaSedyx commented on 4.LastFM/js/usageExample.js
> +var loader4 = new ArtistSearchLoader({page:2, limit:5, artist:'Алла Пугачёва'});
space after `:`

2017-05-08 14:06 UTC, NikitaSedyx commented on 4.LastFM/js/artistInfoLoader.js
> +    if(this.isMbid(this.params.mbid)) {
looks like wrong indent

2017-05-08 14:06 UTC, NikitaSedyx commented on 4.LastFM/js/artistSearch.js
> +      encodeURIComponent(this.params.page) + '&limit=' +
2 spaces for indent

2017-05-08 14:26 UTC, merged